(in-package :postabon-helper)

(defun get-current-commit (r)
  (assert (cl-fad:directory-exists-p r))
  (let* ((dot-git (merge-pathnames ".git/" r))
	 (head (merge-pathnames "HEAD" dot-git)))
    (assert (and (cl-fad:directory-exists-p dot-git)
		 (cl-fad:file-exists-p head)))
    (multiple-value-bind (whole match)
	(cl-ppcre:scan-to-strings "ref:\\s+(.*)$" (trim (slurp (merge-pathnames "HEAD" dot-git))))
      (declare (ignore whole))
      (assert (not (null (aref match 0))))
      (let ((ref (merge-pathnames (aref match 0) dot-git)))
	(assert (cl-fad:file-exists-p ref))
	(trim (slurp ref))))))